[GLOBAL]
pants_version = "2.29.0"
backend_packages.add = [
    "pants.backend.build_files.fmt.ruff",
    "pants.backend.awslambda.python",
    "pants.backend.python",
    "pants.backend.python.lint.docformatter",
    "pants.backend.experimental.python.lint.ruff.check",
    "pants.backend.experimental.python.lint.ruff.format",
    "pants.backend.python.typecheck.mypy"
]
pants_ignore = [
    '.devcontainer/**',
    '.vscode/**',
    'context/**'
]

[source]
root_patterns = [
    "src/*", "test/*"
]

[python]
interpreter_constraints = ["==3.12.*"]
enable_resolves = true
resolves = { python-default = "python-default.lock"}

[python-bootstrap]
#  https://www.pantsbuild.org/docs/python-interpreter-compatibility#changing-the-interpreter-search-path.
search_path = ["<PATH>", "<PYENV>"]

[python-infer]
use_rust_parser = true

[update-build-files]
formatter="ruff"